version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234 # 請更改為你的密碼
      - POSTGRES_DB=company_data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  scraper:
    build: .
    container_name: scraper
    environment:
      - POSTGRES_HOST=postgres # 與服務名稱一致
      - POSTGRES_PORT=5432
      - POSTGRES_DB=company_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234 # 請更改為你的密碼
      - DISPLAY=:99 # 確保 Xvfb 顯示環境變數設置正確
    volumes:
      - ./downloads:/app/downloads
      - ./:/app # 添加當前目錄掛載，方便開發
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "8888:8888" # 為 Jupyter Lab 暴露埠號

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge